//
//  MyStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 06/03/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MyStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* todayIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* boxIconTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* extrasTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* recipeTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* deslogarTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addHelpTextTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* addHelpMessageBoxTargets;

// Colors
+ (UIColor*)iconColor;

// Drawing Methods
+ (void)drawAddHelpText;
+ (void)drawAddHelpMessageBox;

// Generated Images
+ (UIImage*)imageOfTodayIcon;
+ (UIImage*)imageOfBoxIcon;
+ (UIImage*)imageOfExtras;
+ (UIImage*)imageOfRecipe;
+ (UIImage*)imageOfDeslogar;
+ (UIImage*)imageOfAddHelpText;
+ (UIImage*)imageOfAddHelpMessageBox;

@end
