# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SmartPill' do
pod 'Facebook-iOS-SDK', '~> 3.20'
end

target 'SmartPillTests' do

end

